{
    "docs": "https://docs.ansible.com/ansible-core/2.14/dev_guide/testing/sanity/pylint.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test pylint` [[explain](https://docs.ansible.com/ansible-core/2.14/dev_guide/testing/sanity/pylint.html)] failed with 1 error:", 
            "output": "plugins/modules/apigee_env.py:66:24: undefined-variable: Undefined variable 'response'"
        }
    ], 
    "verified": false
}
